# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='deck_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='deck',
            old_name='deck_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='card',
            name='card_definition',
        ),
        migrations.RemoveField(
            model_name='card',
            name='card_term',
        ),
        migrations.AddField(
            model_name='card',
            name='definition',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='card',
            name='term',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
